//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.14 at 08:06:15 PM PDT 
//


package org.onebusaway.siri;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.onebusaway.siri package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.onebusaway.siri
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OneBusAwayAffectsStructure }
     * 
     */
    public OneBusAwayAffectsStructure createOneBusAwayAffectsStructure() {
        return new OneBusAwayAffectsStructure();
    }

    /**
     * Create an instance of {@link OneBusAwayConsequence }
     * 
     */
    public OneBusAwayConsequence createOneBusAwayConsequence() {
        return new OneBusAwayConsequence();
    }

    /**
     * Create an instance of {@link OneBusAwayConsequenceStructure }
     * 
     */
    public OneBusAwayConsequenceStructure createOneBusAwayConsequenceStructure() {
        return new OneBusAwayConsequenceStructure();
    }

    /**
     * Create an instance of {@link OneBusAwayVehicleActivity }
     * 
     */
    public OneBusAwayVehicleActivity createOneBusAwayVehicleActivity() {
        return new OneBusAwayVehicleActivity();
    }

    /**
     * Create an instance of {@link OneBusAwayVehicleActivityStructure }
     * 
     */
    public OneBusAwayVehicleActivityStructure createOneBusAwayVehicleActivityStructure() {
        return new OneBusAwayVehicleActivityStructure();
    }

    /**
     * Create an instance of {@link OneBusAwayAffects }
     * 
     */
    public OneBusAwayAffects createOneBusAwayAffects() {
        return new OneBusAwayAffects();
    }

    /**
     * Create an instance of {@link OneBusAwayAffectsStructure.Applications }
     * 
     */
    public OneBusAwayAffectsStructure.Applications createOneBusAwayAffectsStructureApplications() {
        return new OneBusAwayAffectsStructure.Applications();
    }

    /**
     * Create an instance of {@link AffectedApplicationStructure }
     * 
     */
    public AffectedApplicationStructure createAffectedApplicationStructure() {
        return new AffectedApplicationStructure();
    }

}
