//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.14 at 08:06:15 PM PDT 
//


package org.onebusaway.siri;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Custom structure capturing our extensions to the SIRI VM VehicleActivity element.
 * 
 * <p>Java class for OneBusAwayVehicleActivityStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OneBusAwayVehicleActivityStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Layover" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OneBusAwayVehicleActivityStructure", propOrder = {
    "layover"
})
@XmlSeeAlso({
    OneBusAwayVehicleActivity.class
})
public class OneBusAwayVehicleActivityStructure {

    @XmlElement(name = "Layover")
    protected boolean layover;

    /**
     * Gets the value of the layover property.
     * 
     */
    public boolean isLayover() {
        return layover;
    }

    /**
     * Sets the value of the layover property.
     * 
     */
    public void setLayover(boolean value) {
        this.layover = value;
    }

}
