//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.14 at 08:06:15 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://onebusaway.org/siri", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.onebusaway.siri;
